---

  - name: 3.1.1 Disable IP Forwarding (Scored)
    sysctl: >
      name=net.ipv4.ip_forward
      value={{net_ipv4_ip_forward}}
      state=present
    tags:
      - section3
      - section3.1
      - section3.1.1

  - name: 3.1.2 Disable Send Packet Redirects
    sysctl: >
      name=net.ipv4.conf.all.send_redirects
      value=0
      state=present
    tags:
      - section3
      - section3.1
      - section3.1.2

  - name: 3.1.3 Disable Send Packet Redirects
    sysctl: >
      name=net.ipv4.conf.default.send_redirects
      value=0
      state=present
    tags:
      - section3
      - section3.1
      - section3.1.3
