---

  - name: 1.3.1 Ensure AIDE is installed
    apt: name=aide state=present
    register: aide_installed
    when: use_aide == True
    tags:
      - section1
      - section1.3
      - section1.3.1

  - name: 1.3.2 Ensure AIDE is installed (init)
    command: aideinit
    when:
      - use_aide == True
      - aide_installed.changed == True
    tags:
      - section1
      - section1.3
      - section1.3.2

  - name: 1.3.3 Ensure AIDE is installed - Install AIDE
    stat: path=/var/lib/aide/aide.db.new
    register: aide_db_path
    when:
      - use_aide == True
      - aide_installed.changed == True
    tags:
      - section1
      - section1.3
      - section1.3.3

  - name: 1.3.4 Ensure AIDE is installed - Install AIDE (copy db)
    command: mv /var/lib/aide/aide.db.new /var/lib/aide/aide.db
    when:
      - use_aide == True
      - aide_installed.changed == True
      - aide_db_path.stat.exists == True
    tags:
      - section1
      - section1.3
      - section1.3.4

