---

  - include: section_03_1.yml
    tags:
      - section03
      - _1

  - include: section_03_2.yml
    tags:
      - section03
      - _2

  - include: section_03_3.yml
    tags:
      - section03
      - _3

  - include: section_03_4.yml
    tags:
      - section03
      - _4

  - include: section_03_5.yml
    tags:
      - section03
      - _5

  - include: section_03_6.yml
    tags:
      - section03
      - _6

  - include: section_03_7.yml
    tags:
      - section03
      - _7

